### ISSUE TITLE
[Step 1] 검색 폼 구현을 위한 전략 

### ISSUE THREAD

**Issue by seong-dodo** [seong-dodo/github-finder-program#2]
# ⛳ Step 1 검색 폼 구현

## TODO 검색 폼 구현
- [x] 검색 입력폼이 그려진다.
 
        placeholder="사용자 검색"

## TODO 검색 폼 이벤트
- [x] 검색어를 입력하고 엔터 키보드를 누를수 있다 .
- [x] 입력값이 없는 상태에서 엔터 키보드를 누르면 알림창을 띄워 사용자에게 알려준다.

          alert("값을 입력해주세요.")

- [x] 엔터 키보드를 누르고 나면 입력폼 입력값이 초기화된다.
- [x] 검색어를 입력하고 찾기 버튼을 클릭할 수 있다.
- [x] 입력값이 없는 상태에서 찾기 버튼 클릭라면 알림창을 띄워 사용자에게 알려준다. 

          alert("값을 입력해주세요.")

- [x] 클릭을 하고 나면 입력폼 입력값이 초기화된다.
