### ISSUE TITLE
[Step 2] 서버 리스트 구현을 위한 전략

### ISSUE THREAD

**Issue by seong-dodo** [seong-dodo/github-finder-program#3]
# ⛳ Step 2 서버 리스트 구현

## TODO 검색 리스트 서버 요청 및 응답 받기
- [x] 찾기 버튼을 클릭 및 엔터 키보드 눌렀을 경우 깃허브 사용자 api 서버 요청을 보낸다. 

       method : GET
       쿼리스트링 : 사용자 검색한 이름

- [x] 깃허브 사용자 리스트를 최대 100까지 받아온다.
- [x] 깃허브 각각의 사용자의 프로필 이미지, 사용자 이름을 받아와서 리스트를 그려준다.

## TODO 즐겨찾기 추가
- [x] 각 사용자의 즐겨찾기 버튼을 클릭하면 로컬 저장소에 저장한다.

       데이터 스키마 명세서 : { key : 'user', value: [ { avatar_url: userImageUrl, login: userId } ] 

- [x] 즐겨찾기 버튼을 클릭하면  class="far" 삭제되고 class="fas" 추가되고 즐겨찾기 버튼의 배경색이 검정으로 변경된다.

## TODO 즐겨찾기 해제
- [x] 즐겨찾기 된 사용자의 즐겨찾기 버튼을 클릭하면 로컬 저장소 저장 리스트에서 제외한다.
- [x]  class="fas" 삭제되고 class="far" 추가되고 즐겨찾기 버튼의 배경색이 투명으로 변경된다.
