### ISSUE TITLE
[Step 3] 탭 기능 구현을 위한 전략

### ISSUE THREAD

**Issue by seong-dodo** [seong-dodo/github-finder-program#4]
# ⛳ Step 3 탭 기능 구현

### 깃허브 탭 타입일 경우
- [x] 깃허브 탭의 class="active"가 추가되고 탭의 테두리가 생긴다.
- [x] 즐겨찾기 탭의 class="active"가 사라지고 탭의 테두리 없어진다.
- [x] 입력폼 입력값이 초기화된다.
- [x] 검색 입력폼만 보여진다.
- [x] 검색어를 찾기하면 서버리스트가 그려진다.

### 즐겨찾기 탭 타입일 경우
- [x] 즐겨찾기 탭의 class="active"가 추가되고 탭의 테두리가 생긴다.
- [x] 깃허브 탭의 class="active"가 사라지고 탭의 테두리 없어진다.
- [x] 입력폼 입력값이 초기화된다.

## TODO 페이지 접근시 최초 화면
- [x] 초기 화면 탭은 깃허브 타입 탭이 그려진다.
