### ISSUE TITLE
[Step 4] 로컬 리스트 구현을 위한 전략

### ISSUE THREAD

**Issue by seong-dodo** [seong-dodo/github-finder-program#5]
# ⛳  Step 4 로컬 리스트 구현

### 로컬스토리지에 저장된 리스트가 있을 경우
- [x] 로컬스토리지에 저장된 리스트를 그려준다.

### 찾기 버튼을 클릭했을 경우
- [x] 로컬스토리지에 저장된 리스트와 일치하는 리스트를 그려준다.

### 로컬스토리지에 저장된 리스트가 없을 경우
- [x] '즐겨찾기 리스트가 없습니다'가 그려진다.

## TODO 즐겨찾기 해제
- [x] 사용자의 즐겨찾기 버튼을 클릭하면 리스트에서 지워지고 로컬 저장소 리스트에서 제외한다.
